version: '3'

services:
    app:
        build: .
        restart: always
        volumes:
            - ./:/work
        ports:
            - '3000:3000'
        links:
            - db_postgres
        depends_on: 
            - db_postgres
        command: npm run dev
    db_postgres:
        image: postgres:13.3-alpine
        restart: always
        volumes:
            - /usr/goomer-lista-rango/data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        environment: 
            POSTGRES_USER: 'admin'
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: 'goomer-lista-rango'
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080