version: '3'

services:
    db_postgres:
        image: postgres:13.3-alpine
        restart: always
        volumes:
            - /usr/goomer-lista-rango/data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        environment: 
            POSTGRES_USER: 'admin'
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: 'goomer-lista-rango'